config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root "homes#top"
    post 'genres/create'
    patch 'items/:id' => 'items#update', as: 'update_item'
  end
  
  scope module:  :public, shallow: true do
    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
    get '/orders/complete' => 'orders#complete', as: 'complete'
    post '/orders/comfirm' => 'orders#comfirm', as: 'comfirm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    get "/customers/my_page" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    resources :items, only: [:index, :show]
    resources :homes, only: [:top, :about]
    root to: 'homes#top'
    get "/about" => "homes#about", as: "about"
    # 退会確認画面
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items   
  has_many :orders
  has_many :deliveries
         
  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end       
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  
  def delivery_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
   
   belongs_to :genre
   has_many :cart_items
   has_many :order_details
   
   def with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { cannot_start: 0, waiting_for_production: 1, production: 2, production_completed: 3 }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
     redirect_to admin_genres_path
  end
  
  private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    if params[:by_customer_orders]
      @orders = Order.where(name: params[:by_customer_orders])
    else
      @orders = Order.page(params[:page])
    end
      @total_amount = 0
  end  
  
private

  def order_params
  params.require(:order).permit(:customer_id, :delivery_address_postal_code, :delivery_address, :delivery_address_name, :payment_method, :delivery_charge, :billing_amount, :status)
  end  
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end 
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end
  
  def show
    @item = Item.find(params[:id])
  end  
  
  def index
    @items = Item.page(params[:page])
  end  
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end  
  
  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)  
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @total = 0
    @total_amount = 0
    @name = @order.customer.last_name + @order.customer.first_name
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    
    @order_details.each do |order_detail|
      if @order.status == "payment_confirmation"
        order_detail.update(making_status:"waiting_for_production")
      end
    end
    redirect_to admin_order_path
  end
  
private

  def order_params
  params.require(:order).permit(:customer_id, :delivery_address_postal_code, :delivery_address, :delivery_address_name, :payment_method, :postage, :billing_amount, :status)
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end

  def order_detail_params
    params.require(:order_detail).permit(:item_id, :order_id, :amount, :purchase_price, :making_status)  
  end
  
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # def after_sign_up_path_for(resource)
  # case resource
  # when Admin
  #   admin_root_path
  # when Customer
  #   customers_my_page_path
  # end
  # end

  def after_sign_out_path_for(resource)
    case resource
    when :admin   # ログアウト時はシンボルが返ってくる
      new_admin_session_path
    when :customer  # ログアウト時はシンボルが返ってくる
      root_path
    end
  end 
  
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<p></p>

<div class="container">
  <div class ="col-md-3">
    <h4 class ="bg-light", align="center">ジャンル編集</h4>
  </div>
  
    <div class ="col-md-8">
      <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch  do |f| %>
        <%= f.label :ジャンル名, class:"mr-5 mt-5 mb-5" %>
        <%= f.text_field :name,autocomplete: "name", class:"mr-5"  %>
        <%= f.submit "変更を保存", class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>
    

app/views/admin/genres/index.html.erb
<p></p>

<div class="container">
  <div class ="col-md-3">
    <h4 class ="bg-light", align="center">ジャンル一覧・追加</h4>
  </div>
  
    <div class ="row">
      <div class ="col-md-6">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <%= f.label :"ジャンル名", class:"mr-5 mt-5 mb-5" %>
        <%= f.text_field :name, autofocus: true, placeholder: "ジャンル名", class:"mr-5 ml-5" %>
        <%= f.submit "新規登録", :class =>'btn btn-success' %>
      <% end %>
      </div>
  </div>

  <div  class="col-md-4">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th colspan="2">ジャンル</th>
        </tr>
      </thead>
      <tbody>  
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
          </tr>
        <% end %>  
      </tbody> 
    </table>
  </div>
</div>  
        

app/views/admin/items/edit.html.erb
<p></p>

<div class="container">
  <div class ="col-md-3">
    <h3 class ="bg-light", align="center">商品編集</h3>
  </div>

  <div class ="row">
    <div class ="mx-auto">
    <%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>
    <table style="border:none;", :class="table" >
    <tbody>
      <tr>
        <td width="130" height="40">商品画像</td>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr class="field">
        <td valign="middle"  height="40"><%= f.label :"商品名" %></thd>
        <td><%= f.text_field :name, autocomplete: "name",size:"35" %></td>
      </tr>
      <tr class="field">
        <td height="40"><%= f.label :"商品説明" %></td>
        <td><%= f.text_area :introduction, autocomplete: "introduction", size:"37x6" %></td>
      </tr>
      <tr class="form-group">
        <td height="40"><%= f.label  'ジャンル' %></td>
        <td><%= f.collection_select :genre_id, Genre.all, :id,:name, {include_blank:"--選択してください--"}, style:"width:300px;" %></td>
      </tr>
      <tr class="field">
        <td valign="middle" height="50"><%= f.label :"税抜価格" %></td>
        <td><%= f.text_field :price, autocomplete: "price", size:"35" %>円</td>
      </tr>
      <tr class="field">
        <td height="50"><%= f.label :"販売ステータス  " %></td>
        <td><%= f.radio_button :is_active, "TRUE", {:checked => true}  %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, "FALSE" %>
            <%= f.label :is_active, "販売停止中" %></td>
      </tr>
      <tr>
        <td colspan="2", class ="text-center"><%= f.submit "変更を保存", :class =>'btn btn-success btn-lg' %></th>
          
      </tr>
      
    </tbody>
    </table>
    <% end %>
  </div>
  </div>
</div>  

app/views/admin/items/index.html.erb
<p></p>

<div class="container">
  <div class ="col-md-3">
    <h4 class ="bg-light", align="center">商品一覧</h4>
  </div>
  
  <h3 class="text-right">
    <%= link_to new_admin_item_path do %>
    <span class ="text-body shadow-sm rounded-circle">＋</span>
    <% end %>
  </h3>
  
  <div class ="row">         
    <table class="table table-hover table-inverse">
      <thead class ="bg-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>  
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item) do %>
            <span class ="text-body border-bottom border-dark"><%= item.name %></span>
            <% end %>
          </td>
          <td><%= item.price  %></td>
          <td><%= item.genre.name %></td>
          <td><% if item.is_active %>
            <span class ="text-success font-weight-bold">販売中</span>
            <% else %>
            <span class ="text-secondary font-weight-bold">販売停止中</span>
            <% end %>
          </td>
        </tr>
       <% end %>  
      </tbody> 
    </table>
  </div>
  <div class=" col-md-12 d-flex justify-content-center"><%= paginate @items %></div>
</div>

app/views/admin/items/new.html.erb
<p></p>

<div class="container">
  <div class ="col-md-3">
    <h3 class ="bg-light", align="center">商品新規登録</h3>
  </div>


  <div class ="row">
    <div class ="mx-auto">
    <%= form_with model: @item, url: admin_items_path do |f| %>
    <table style="border:none;", :class="table" >
    <tbody>
        <tr>
          <th>商品画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr class="field">
          <th valign="middle"><%= f.label :"商品名" %></th>
          <td><%= f.text_field :name, autocomplete: "name",placeholder: "商品名", size:"35" %></td>
        </tr>
        <tr class="field">
          <th><%= f.label :"商品説明" %></th>
          <td><%= f.text_area :introduction, autocomplete: "introduction", placeholder: "ここに説明文を記述します", size:"37x6" %></td>
        </tr>
        <tr class="form-group">
          <th><%= f.label  'ジャンル' %></th>
          <td><%= f.collection_select :genre_id, Genre.all, :id,:name, {include_blank:"--選択してください--"}, style:"width:300px;" %></td>
        </tr>
        <tr class="field">
          <th valign="middle"><%= f.label :"税抜価格" %></th>
          <td><%= f.text_field :price, autocomplete: "price", placeholder: "1000", size:"35" %>円</td>
        </tr>
        <tr class="field">
          <th><%= f.label :"販売ステータス" %></th>
          <td><%= f.radio_button :is_active, "TRUE", {:checked => true}  %>
              <%= f.label :is_active, "販売中" %>
          <%= f.radio_button :is_active, "FALSE" %>
          <%= f.label :is_active, "販売停止中" %></td>
        </tr>
        <tr>
          <td colspan="2", class ="text-center"><%= f.submit '新規登録', class: "btn btn-success btn-lg" %></td>
        </tr>
      
    </tbody>
   </table>
   <% end %>
  </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<p></p>

<div class="container">
  <div class ="col-md-3">
    <h3 class ="bg-light", align="center">商品詳細</h3>
  </div>
  
  <div class ="row">
    <div class ="col-md-3 mr-0">
      <%= image_tag @item.image, size: "250x180" %>
    </div>
    <div class ="col-md-5 ml-0">
      <table class ="table table-borderless">
        <tbody>

          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>

            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td>税込価格  <br/>（税抜価格）</td>
            <td><%= @item.with_tax_price %> ( <%= @item.price %> )円</td>
          </tr>
          <tr>
            <td  nowrap>販売ステータス</td>
            <td>
              <% if @item.is_active == true %>
              <span class ="text-success font-weight-bold">販売中</span>
              <% else %>
              <span class ="text-secondary font-weight-bold">販売停止中</span>
              <% end %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td class="text-left"><%= link_to '編集する', edit_admin_item_path, class:"btn btn-success btn-lg" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<p></p>

<div class="container">
  <div class ="col-md-3">
    <h4 class ="bg-light", align="center">注文履歴詳細</h4>
  </div>
  
  <div class="row">
    <div class="mt-3">
    <div class="col-md-12">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to @name, admin_customer_path(@order.customer_id), method: :get, class:"text-body" %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <span><%= @order.delivery_address_postal_code %> <%= @order.delivery_address %></span><br />
            <span><%= @order.delivery_address_name %></span>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
            <%= f.select :status, Order.statuses_i18n.keys.map{|k| [I18n.t("enums.order.status.#{k}"), k]} %><%= f.submit'更新', class:"btn btn-success btn-sm ml-4" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    </div>
    </div>
  </div>

  <div class="row">
  <div class="col-md-8 mt-4">
    <table class ="table table-borderless border-top border-bottom">
        <thead class ="bg-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.purchase_price %></td>
            <td><%= order_detail.amount %></td>
            <% @total_amount += order_detail.amount %>
            <td><%= order_detail.purchase_price * order_detail.amount %></td>
            <% @total += order_detail.purchase_price * order_detail.amount %>
            <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f| %>
            <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %><%= f.submit'更新', class:"btn btn-success btn-sm ml-4" %>
            <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
    </table>
  </div>

    <div class ="col-md-3 mt-5">
    <table class ="table table-borderless">
      <tbody>
        <tr>
          <th>商品合計</th>
          <td><%= @total_amount %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.delivery_charge %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <th><%= @order.delivery_charge + @total %></th>
        </tr>
      </tbody>
    </table>
  </div>
  </div>


</div>