config/routes.rb
Rails.application.routes.draw do
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  
  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root "homes#top"
    post 'genres/create'
    patch 'items/:id' => 'items#update', as: 'update_item'
  end
  
  scope module:  :public, shallow: true do
    resources :deliveries, only: [:index, :create, :edit, :update, :destroy]
    get '/orders/complete' => 'orders#complete', as: 'complete'
    post '/orders/comfirm' => 'orders#comfirm', as: 'comfirm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    get "/customers/my_page" => "customers#show"
    get "/customers/information/edit" => "customers#edit"
    patch "/customers/information" => "customers#update"
    resources :items, only: [:index, :show]
    resources :homes, only: [:top, :about]
    root to: 'homes#top'
    get "/about" => "homes#about", as: "about"
    # 退会確認画面
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items   
  has_many :orders
  has_many :deliveries
         
  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end       
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer
  
  def delivery_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
   
   belongs_to :genre
   has_many :cart_items
   has_many :order_details
   
   def with_tax_price
    (price * 1.1).floor
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { cannot_start: 0, waiting_for_production: 1, production: 2, production_completed: 3 }
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
     redirect_to admin_genres_path
  end
  
  private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    if params[:by_customer_orders]
      @orders = Order.where(name: params[:by_customer_orders])
    else
      @orders = Order.page(params[:page])
    end
      @total_amount = 0
  end  
  
private

  def order_params
  params.require(:order).permit(:customer_id, :delivery_address_postal_code, :delivery_address, :delivery_address_name, :payment_method, :delivery_charge, :billing_amount, :status)
  end  
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end 
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end
  
  def show
    @item = Item.find(params[:id])
  end  
  
  def index
    @items = Item.page(params[:page])
  end  
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end  
  
  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # def after_sign_up_path_for(resource)
  # case resource
  # when Admin
  #   admin_root_path
  # when Customer
  #   customers_my_page_path
  # end
  # end

  def after_sign_out_path_for(resource)
    case resource
    when :admin   # ログアウト時はシンボルが返ってくる
      new_admin_session_path
    when :customer  # ログアウト時はシンボルが返ってくる
      root_path
    end
  end 
  
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <% if customer_signed_in? %>
        <%= link_to root_path, class:"navbar-brand" do %>
          <h2>NaganoCake</h2>
        <% end %>  
      <% elsif admin_signed_in? %>
          <h2>NaganoCake</h2>
      <% else %>
        <%= link_to root_path, class:"navbar-brand" do %>
          <h2>NaganoCake</h2>
        <% end %>
      <% end %>    
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          
          
          <% if customer_signed_in? %>
          
          
          <li class="mr-5">
            <%= link_to customers_my_page_path , class:"btn btn-outline-secondary text-dark" do %>マイページ
            <% end %>
          </li>
          
          <li class="mr-5">
            <%= link_to items_path , class:"btn btn-outline-secondary text-dark" do %>商品一覧
            <% end %>
          </li>
          <li class="mr-5">
            <%= link_to cart_items_path , class:"btn btn-outline-secondary text-dark" do %>カート
            <% end %>
          </li>
          <li class="mr-5">
            <%= link_to destroy_customer_session_path, method: :delete , class:"btn btn-outline-secondary text-dark" do %>ログアウト
            <% end %>
          </li>
          
          <% elsif admin_signed_in? %>
          
          <li class="mr-3">
            <%= link_to admin_items_path , class:"btn btn-outline-secondary text-dark" do %>商品一覧
            <% end %>
          </li>
          
          <li class="mr-3">
            <%= link_to admin_customers_path , class:"btn btn-outline-secondary text-dark" do %>会員一覧
            <% end %>
          </li>
          
          <li class="mr-3">
            <%= link_to admin_root_path, class:"btn btn-outline-secondary text-dark" do %>注文履歴一覧
            <% end %>
          </li>
          <li class="mr-3">
            <%= link_to admin_genres_path, class:"btn btn-outline-secondary text-dark" do %>ジャンル一覧
            <% end %>
          </li>
          <li class="mr-3">
            <%= link_to destroy_admin_session_path, method: :delete , class:"btn btn-outline-secondary text-dark" do %>ログアウト
            <% end %>
          </li>
          
          <% else %>
          <li class="mr-5">
            <%= link_to about_path, class:"btn btn-outline-secondary text-dark" do %>adout
            <% end %>
          </li>
          <li class="mr-5">
            <%= link_to items_path, class:"btn btn-outline-secondary text-dark"  do %>商品一覧
            <% end %>      
          </li>
          <li class="mr-5">
            <%= link_to new_customer_registration_path, class:"btn btn-outline-secondary text-dark"  do %>新規登録
            <% end %>      
          </li>
          <li class="mr-5">
            <%= link_to customer_session_path, class:"btn btn-outline-secondary text-dark"  do %>ログイン
            <% end %>         
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
    <%= yield %>
  </body>
</html>